var OA_output = new Array(); 
OA_output['1'] = '';
OA_output['1'] += "<"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['1'] += "<"+"!-- 侧栏矩形 -->\n";
OA_output['1'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['1'] += "style=\"display:inline-block;width:255px;height:213px\"\n";
OA_output['1'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['1'] += "data-ad-slot=\"9674628595\"><"+"/ins>\n";
OA_output['1'] += "<"+"script>\n";
OA_output['1'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['1'] += "<"+"/script><"+"div id=\'beacon_be14f73a91\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=1&amp;campaignid=1&amp;zoneid=1&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=be14f73a91\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['2'] = '';
OA_output['2'] += "<"+"div style=\"line-height: 0; background: #FAFAFA\">\n";
OA_output['2'] += "<"+"div class=\"container text-center\" style=\"position: relative;\">\n";
OA_output['2'] += "<"+"a href=\"https://segmentfault.com/user/login\" class=\"small text-muted\" style=\"position: absolute; top: 10px; right: 15px;\">登录免广告<"+"/a><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['2'] += "<"+"!-- 导航下横幅广告（大型） -->\n";
OA_output['2'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['2'] += "style=\"display:inline-block;width:970px;height:90px\"\n";
OA_output['2'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['2'] += "data-ad-slot=\"6450634185\"><"+"/ins>\n";
OA_output['2'] += "<"+"script>\n";
OA_output['2'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['2'] += "<"+"/script><"+"div id=\'beacon_98129c4d16\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=43&amp;campaignid=1&amp;zoneid=2&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=98129c4d16\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['2'] += "<"+"/div>\n";
OA_output['3'] = '';
OA_output['3'] += "<"+"div style=\"text-align: center; line-height: 0; background: #FAFAFA\"><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['3'] += "<"+"!-- 中部横幅广告位 -->\n";
OA_output['3'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['3'] += "style=\"display:inline-block;width:728px;height:90px\"\n";
OA_output['3'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['3'] += "data-ad-slot=\"5598290435\"><"+"/ins>\n";
OA_output['3'] += "<"+"script>\n";
OA_output['3'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['3'] += "<"+"/script><"+"div id=\'beacon_650c9eec36\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=2&amp;campaignid=1&amp;zoneid=3&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=650c9eec36\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"div style=\"text-align: center; line-height: 0; background: #FAFAFA;\"><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['4'] += "<"+"!-- 自适应广告 -->\n";
OA_output['4'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['4'] += "style=\"display:block\"\n";
OA_output['4'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['4'] += "data-ad-slot=\"6644962961\"\n";
OA_output['4'] += "data-ad-format=\"auto\"\n";
OA_output['4'] += "data-full-width-responsive=\"true\"><"+"/ins>\n";
OA_output['4'] += "<"+"script>\n";
OA_output['4'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['4'] += "<"+"/script><"+"div id=\'beacon_e1d4a6d87e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=117&amp;campaignid=1&amp;zoneid=4&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=e1d4a6d87e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"div id=\'beacon_fa354b32b2\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=5&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=fa354b32b2\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['6'] = '';
OA_output['6'] += "<"+"div id=\'beacon_5e4ba7e183\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=6&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=5e4ba7e183\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['7'] = '';
OA_output['7'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=56__zoneid=7__cb=8c764ba30c__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011318558\' target=\'_blank\'><"+"strong>大神的PHP 进阶之路<"+"/strong><"+"br>\n";
OA_output['7'] += "<"+"small style=\"color: #999\">亿级 PV 项目的架构梳理，性能提升实战<"+"/small><"+"/a><"+"div id=\'beacon_8c764ba30c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=56&amp;campaignid=14&amp;zoneid=7&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=8c764ba30c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['9'] = '';
OA_output['9'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=47__zoneid=9__cb=9fbc8fa1dd__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000016221751\' target=\'_blank\'><"+"strong>Vue 技术栈开发实战<"+"/strong><"+"br>\n";
OA_output['9'] += "<"+"small style=\"color: #999\">iView 核心开发者带你掌握 Vue 精髓<"+"/small><"+"/a><"+"div id=\'beacon_9fbc8fa1dd\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=47&amp;campaignid=14&amp;zoneid=9&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=9fbc8fa1dd\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';
OA_output['10'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=57__zoneid=10__cb=532d66d6bb__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011387052\' target=\'_blank\'><"+"strong> Java 微服务实践课<"+"/strong><"+"br>\n";
OA_output['10'] += "<"+"small style=\"color: #999\">上千人学习过的微服务实栈课<"+"/small><"+"/a><"+"div id=\'beacon_532d66d6bb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=57&amp;campaignid=14&amp;zoneid=10&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=532d66d6bb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['11'] = '';
OA_output['11'] += "<"+"div id=\'beacon_7e4bee980a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=11&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=7e4bee980a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['12'] = '';
OA_output['12'] += "<"+"div id=\'beacon_7e9b45459e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=12&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=7e9b45459e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['13'] = '';
OA_output['13'] += "<"+"div id=\'beacon_955487d61d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=13&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=955487d61d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['14'] = '';
OA_output['14'] += "<"+"div id=\'beacon_1dd961892c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=14&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=1dd961892c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['15'] = '';
OA_output['15'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=53__zoneid=15__cb=48ea4a38e2__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000016424063\' target=\'_blank\'><"+"strong>iView 实战系列课程<"+"/strong><"+"br>\n";
OA_output['15'] += "<"+"small style=\"color: #999\"><"+"span style=\"color: #F7A700\">[限时优惠]<"+"/span> 知名开源组件库作者讲授<"+"/small><"+"/a><"+"div id=\'beacon_48ea4a38e2\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=53&amp;campaignid=14&amp;zoneid=15&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=48ea4a38e2\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['16'] = '';
OA_output['16'] += "<"+"div id=\'beacon_b37652bf7b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=16&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=b37652bf7b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['17'] = '';
OA_output['17'] += "<"+"div id=\'beacon_2976429cc7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=17&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000019905629&amp;cb=2976429cc7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
